config/routes.rb
Rails.application.routes.draw do
  resources :articles

  root 'articles#index'

  get 'shell-start' => 'appshell#shell_start'
  get 'shell-end' => 'appshell#shell_end'
  get 'shell-start-article' => 'appshell#shell_start_article'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/appshell_controller.rb
class AppshellController < ApplicationController
  def shell_start
    render 'shell_start', :layout => false
  end

  def shell_end
    render 'shell_end', :layout => false
  end

  def shell_start_article
    render 'shell_start_article', :layout => false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    if params[:shell] == 'true'
      render :layout => false
    end
  end

  def show
    @article = Article.find(params[:id])

    if params[:shell] == 'true'
      render :layout => false
    end
  end

  def new
    if params[:shell] == 'true'
      render :layout => false
    end
  end

  def create
    @article = Article.new(article_params)

    @article.save
    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appshell_helper.rb
module AppshellHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/appshell/shell_end.html.erb
<%= render 'layouts/shell_end' %>

app/views/appshell/shell_start.html.erb
<%= render 'layouts/shell_start' %>

app/views/appshell/shell_start_article.html.erb
<%= render 'layouts/shell_start_article' %>

app/views/articles/index.html.erb
<h1>Stories worth talking about.</h1>

<% @articles.each do |article| %>
   <%= link_to article_path(article) do %>
    <div class="card">
      <h3><%= article.title %></h3>
      <p><%= article.text %></p>
    </div>
  <% end %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<img src="https://images.unsplash.com/photo-1474204075013-fafcfee9bfd7?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&s=3ee2598b58ba68f03b8d661db5f4faaf" alt="">
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/layouts/_shell_end.html.erb
</main>

</body>
</html>

app/views/layouts/_shell_start.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medium</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true %>
  <%= csrf_meta_tags %>

  <style>
    * {
      box-sizing: border-box;
    }

    html {
      color: rgba(0,0,0,.8);
      font-family: -apple-system, BlinkMacSystemFont, San Francisco, Roboto, Segoe UI, Helvetica Neue, sans-serif;
      font-size: 16px;
      background: #FAFAFA;
    }

    header {
      width: 100%;
      background: white;
      position: fixed;
      display: flex;
      align-items: center;
      top: 0;
      box-shadow: 0 0 1px rgba(0,0,0,.15);
      min-height: 80px;
      padding: 0 20px;
    }

    .wrapper {
      width: 100%;
      max-width: 1000px;
      margin: 0 auto;
    }

    header .wrapper {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    #logo {
      width: 45px;
      height: 45px;
    }

    main {
      padding-top: 120px;
    }

    .nav li{
      display: inline-block;
    }

    .svg-icon {
      fill: rgba(0,0,0,.44);
    }

    .turbolinks-progress-bar {
      background: rgb(72, 231, 154);
      height: 2px;
    }

    .card {
      background: white;
      border-radius: 3px;
      box-shadow: 0 1px 4px rgba(0,0,0,.04);
      border: 1px solid rgba(0,0,0,0.09);
      max-width: 660px;
      padding: 20px;
      margin-bottom: 10px;
    }
  </style>
</head>
<body>
<header>
  <div class="wrapper">
    <h1>
      <a href="/">
        <svg id="logo" width="256px" height="208px" viewBox="0 0 256 208" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" preserveAspectRatio="xMidYMid">
          <g>
            <path d="M177.735242,1.67620228 C173.837865,-0.18165739 170.650604,1.69271659 170.650604,5.85432226 L170.650604,171.360719 L241.794244,205.322394 C249.622026,209.120685 255.971777,206.478396 255.971777,199.542386 L255.971777,40.1793119 C255.971777,39.5187396 255.55892,38.9407388 254.94789,38.6104526 L177.743499,1.78354529 L177.743499,1.70097375 L177.735242,1.67620228 L177.735242,1.67620228 Z" fill="#32FC8D"></path>
            <path d="M85.3211734,130.636435 L166.488998,4.73960646 C168.784487,1.18903019 173.837865,-0.214686007 177.718728,1.6018879 L255.038719,38.5113668 C255.534148,38.7590814 255.715806,39.3370822 255.426805,39.7499399 L170.642347,171.377233 L85.3211734,130.652949 L85.3211734,130.636435 L85.3211734,130.636435 Z" fill="#0BE370"></path>
            <path d="M11.8077304,3.9221482 C5.31760724,0.825715411 3.1129471,3.12946141 6.91949514,9.04158375 L85.3211734,130.636435 L170.642347,171.360719 L85.5110879,39.3040535 C85.3872306,39.114139 85.2138304,38.9572531 85.0156587,38.8581672 L11.8077304,3.93040535 L11.8077304,3.9221482 L11.8077304,3.9221482 Z" fill="#14C767"></path>
            <path d="M85.3211734,199.476329 C85.3211734,206.412338 80.0118233,209.550057 73.513443,206.445367 L7.08463822,174.737895 C3.18726149,172.888293 0,167.967029 0,163.797166 L0,8.38101142 C0,2.83220386 4.25243436,0.32202901 9.45444145,2.8074324 L84.8670299,38.8086243 C85.1477731,38.9324816 85.3211734,39.2049677 85.3211734,39.5022252 L85.3211734,199.4433 L85.3211734,199.476329 L85.3211734,199.476329 Z" fill="#00AB6C"></path>
          </g>
        </svg>
      </a>
    </h1>

    <ul class="nav">
      <li><svg class="svg-icon" width="25" height="25" viewBox="0 0 25 25"><path d="M20.067 18.933l-4.157-4.157a6 6 0 1 0-.884.884l4.157 4.157a.624.624 0 1 0 .884-.884zM6.5 11c0-2.62 2.13-4.75 4.75-4.75S16 8.38 16 11s-2.13 4.75-4.75 4.75S6.5 13.62 6.5 11z"></path></svg></li>
      <li><svg class="svg-icon" width="25" height="25" viewBox="-293 409 25 25"><path d="M-273.327 423.67l-1.673-1.52v-3.646a5.5 5.5 0 0 0-6.04-5.474c-2.86.273-4.96 2.838-4.96 5.71v3.41l-1.68 1.553c-.204.19-.32.456-.32.734V427a1 1 0 0 0 1 1h3.49a3.079 3.079 0 0 0 3.01 2.45 3.08 3.08 0 0 0 3.01-2.45h3.49a1 1 0 0 0 1-1v-2.59c0-.28-.12-.55-.327-.74zm-7.173 5.63c-.842 0-1.55-.546-1.812-1.3h3.624a1.92 1.92 0 0 1-1.812 1.3zm6.35-2.45h-12.7v-2.347l1.63-1.51c.236-.216.37-.522.37-.843v-3.41c0-2.35 1.72-4.356 3.92-4.565a4.353 4.353 0 0 1 4.78 4.33v3.645c0 .324.137.633.376.85l1.624 1.477v2.373z"></path></svg></li>
      <li>Profile</li>
    </ul>
  </div>
</header>

<main class="wrapper">

app/views/layouts/application.html.erb
<%= render 'layouts/shell_start' %>
<%= yield %>
<%= render 'layouts/shell_end' %>